WORKDIR /usr/src/mymaven

EXPOSE 3330

ENV JAVA_HOME=/usr/java/openjdk-15
ENV JAVA_VERSION=15.0.2
ENV LANG=C.UTF-8
ENV MAVEN_HOME=/usr/share/maven
ENV MAVEN_CONFIG=/root/.m2
ENV PATH=/usr/java/openjdk-15/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#ENTRYPOINT ["./entrypoint.sh"]
ENTRYPOINT ["bash"]
